coverage:
  status:
    project:
      default:
        target: 80% # Minimum 80% coverage
        threshold: 5% # Allow 5% drop
    patch:
      default:
        target: 80% # New code must have 80% coverage

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

ignore:
  - "**/*.g.cs" # Generated files
  - "**/Migrations/**" # EF migrations
  - "**/Program.cs" # Startup files
  - "**/*Tests/**" # Test projects
