coverage:
  status:
    project:
      default:
        target: 80% # Minimum 80% coverage
        threshold: 5% # Allow 5% drop
        if_ci_failed: error
    patch:
      default:
        target: 80% # New code must have 80% coverage
        if_ci_failed: error

comment:
  layout: "header,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: no # Show coverage even without base commit
  require_head: yes

ignore:
  - "**/*.g.cs" # Generated files
  - "**/Migrations/**" # EF migrations
  - "**/Program.cs" # Startup files
  - "**/*Tests/**" # Test projects
